### ISSUE TITLE
free kdtree memory in the GPU

### ISSUE THREAD

**Issue by chronos-ctrl** [gieseke/bufferkdtree#1]
Hi, is there any function that free the allocated kdtree memory in the GPU ?

**Comment by gieseke** [comment]
Hi aminm2a,

the memory for the k-d tree nodes and leaves can be released via the function 'free_train_buffers_gpu' in /src/neighbors/buffer_kdtree/gpu_opencl.c . 

There is no direct Python call for just releasing only these resources. You can use the destructor for the BufferKDTreeNN class to release basically all resources (all training buffers on the host/device, space allocated for temporary buffers, OpenCL kernels, ...).

Is the general destructor useful for you? Or do you need special calls that only release certain buffers/trees on the device?

Cheers
Fabian

**Comment by chronos-ctrl** [comment]
Hi gieseke,

Thanks for your answer, the general destructor is useful for me, but there is no python call for it if I'm not wrong ?

**Comment by gieseke** [comment]
Hi,

yes, you are right. So far, there is no explicit Python function that releases the resources. I will add it in a future release, thanks for pointing out this issue.

At the moment, you could try to call the destructor (e.g., via 'del nbrs' if 'nbrs' is the current model). But there is no guarantee that the destructor is actually called. Releasing the resources explicitly would be the better choice ...

Best
Fabian

**Comment by chronos-ctrl** [comment]
Hi gieske, 

'del nbrs' calls exactly the destructor of BufferKDTreeNN, and so extern_free_resources is called. I noticed that a small chunk of the memory is released but not everything. My observation is that only the memory used for quering is released but the data used to fit the model on the device is not released. Do have an idea about this ? In fact, I need to free everything on the device.

**Comment by gieseke** [comment]
Hi,

have you tried to "import gc" and to call gc.collect() after deleting the model? The memory should be actually released. Will check this soon.

**Comment by chronos-ctrl** [comment]
Nothing change infact with gc.collect(). The memory keep growing. Here is a test example I'm using to see the memory consumption (with 'nvidia-smi' command): 

```
import numpy
import random
from bufferkdtree.neighbors.base import NearestNeighbors
import pdb
import gc

class test():

    def __init__(self):
        self.Xtrain = numpy.random.rand(1000000, 5).astype("float32")
        self.Xtest = numpy.random.rand(1000000, 5).astype("float32")

    def apply(self):
        print ("init..")
        model = NearestNeighbors(algorithm = "buffer_kd_tree", tree_depth=3, plat_dev_ids={0:[0]}, verbose = 0)
        print ("fitting..")
        model.fit(self.Xtrain)
        _, inds = model.kneighbors(self.Xtest, 1)

        # free memory
        del model
        gc.collect()

        return inds

for i in range(100):
    tt = test()
    inds = tt.apply()
```

**Comment by gieseke** [comment]
Hi aminm2a,

it seems that not all the memory is released. It might also be that some other resources are not completely freed...will have a look at it soon!

Best
Fabian

**Comment by gieseke** [comment]
Hi aminm2a,

the bug seems to be fixed: Both the "fitting" and "querying" resources were not released correctly in case the functions were repeatedly called. Your example now runs without leaking memory ...

Best
Fabian

**Comment by chronos-ctrl** [comment]
It works great. 

Thanks :+1:
